### PR TITLE
Fix operating system names

### PR DESCRIPTION
**Pull request by TaylanUB**
Consistently use "GNU/Linux" to refer to GNU/Linux, and "OS X" to refer
to OS X ("Mac OS X" is the old name).

News pages remain untouched.

### CODE REVIEW

**Comment by Thynix** [comment]
/ is now used as both a separator between names and within a name. Thoughts on using & or something between names?

**Comment by TaylanUB** [comment]
The Spanish site uses "GNU/Linux - Unix" (it was already using "GNU/Linux" there).  We could imitate that, or we could make it all use &.  Probably & is better.  Will push a commit in a moment; tell me if I should revert/change it.

**Comment by Thynix** [comment]
Deployed, thanks!

**Comment by Medrado** [comment]
index.php corrected

**Comment by Thynix** [comment]
@Medrado I'm sorry, I don't understand what you mean. Can you elaborate please?

**Comment by Medrado** [comment]
Hi Thynix !
Sorry. I wanted to say I enjoyed the adequacy of names GNU/Linux to replace the Linux-Unix. I found much more relevant and current , so I have corrected the pages (index and download).
I had done translations and had not noticed .

**Comment by Thynix** [comment]
@Medrado Ah, okay, I understand now. I've added your changes as 683d0f0f4a1d575a3f631330bf9743ce7de5d8f7, 3ef7b1faa9e936268ac069554cb0ffee97a6b026, and  61c7595ee8e7dc4005c8a633e75b708bf25be2b3, and fixed a problem that prevented the documentation page from rendering in e491ef30e859fd0a9a4b38d17f2afd19ee63ff3e. It is [deployed](https://freenetproject.org/?language=pt-br) now.

In the future can you please submit changes with a [pull request](https://help.github.com/articles/using-pull-requests/#initiating-the-pull-request) against the branch `next`?

**Comment by Medrado** [comment]
OK, @Thynix.  I'm still learning how to work with Git , so I make some mistakes here . Excuse me.

**Comment by Thynix** [comment]
No worries.

**Pull request merged**
