### PR TITLE
index: include latestnews.php in all translations

### PR DESCRIPTION
**Pull request by ArneBab**
This resolves the stale news on translated pages.

Translated news can be added on the index page in addition to the included news.

### CODE REVIEW

**Comment by Thynix** [comment]
Ooh, good idea. I begrudgingly admit that PHP made this easier to do than I would have thought.

**Comment by Thynix** [comment]
Though this looks like it should work it actually doesn't. I'm looking into why. During the build it outputs:

```
PHP Notice:  page=latestnews file=/home/operhiem1/website/includes/latestnews.inc.php in /home/operhiem1/website/includes/common.inc.php on line 81
PHP Notice:  Undefined variable: pages in /home/operhiem1/website/includes/common.inc.php on line 86
```

Having something that's actually practical to test with instead of this pile of PHP and Bash would be helpful, but that's for the rewrite if we ever get around to it.

**Comment by Thynix** [comment]
I think I have discovered two things:
1. `include`-ing a nonexistent file fails silently.
2. All files under a language are expected to have a counterpart in `includes/$page.inc.php`.

EDIT:

1 is unlikely to be true. 2 is true.

**Comment by Thynix** [comment]
Whoops. I was not looking at the test site.

**Comment by Thynix** [comment]
It worked all along. Thanks! Deployed!

**Comment by ArneBab** [comment]
no problem - thank you for testing this! I used ./make-pages, but could only test the generated sites with lynx.

I still think that this solution is a hack, since it entangles the languages and does not allow sorting entries from different sources by date, but it works and is extremly simple. We just need to take care not to try to make this elegant and clever, otherwise I fear that it would grow horrible. It even relies on putting non-english new entries into the index pages, with a notice to do that in the page itself to keep people from doing clever (but dangerous) things. But it works and it is about as low maintenance as we can make it without introducing complexity (which people would have to understand to maintain the pages).

And thank you for deploying it

**Pull request merged**
